### ISSUE TITLE
Bug copying models with quadratic expressions

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2425]
When trying to copy a model that contains quadratic expressions, I am getting this error:
 `ERROR: MethodError: no method matching getindex(::ReferenceMap, ::Array{GenericQuadExpr{Float64,VariableRef},1})` 

_Originally posted by @linde-fr in https://github.com/jump-dev/JuMP.jl/issues/2371#issuecomment-756219361_

**Comment by odow** [comment]
Hi @linde-fr, I've opened this in a new issue so we can discuss.

I think I already fixed this: https://github.com/jump-dev/JuMP.jl/pull/2405

Can you try (in a new Julia session)
```Julia
] add JuMP#master

# Then run your code
```

To get back to a released version of JuMP, use 
```Julia
] free JuMP
```

**Comment by linde-fr** [comment]
Thanks for following up!
I did as you said. Pkg.status now gives 
`JuMP v0.21.5 `https://github.com/jump-dev/JuMP.jl.git#master`

I still get the same
`MethodError: no method matching getindex(::ReferenceMap, ::Array{GenericQuadExpr{Float64,VariableRef},1})`
when trying to copy a model that includes a Quadratic Expression.

When I change the expression to an affine one, I get
`ERROR: MethodError: no method matching getindex(::ReferenceMap, ::Array{GenericAffExpr{Float64,VariableRef},1})`

**Comment by odow** [comment]
You need to start a new Julia session so that you don't have the old version of JuMP still in memory.
```Julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x)
x

julia> @expression(model, ex[i=1:2], i * x^2 + i * x + i)
2-element Array{GenericQuadExpr{Float64,VariableRef},1}:
 x² + x + 1
 2 x² + 2 x + 2

julia> new_model, ref_map = copy_model(model)
(A JuMP Model
Feasibility problem with:
Variable: 1
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.
Names registered in the model: ex, x, ReferenceMap(A JuMP Model
Feasibility problem with:
Variable: 1
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.
Names registered in the model: ex, x, MathOptInterface.Utilities.IndexMap(MathOptInterface.VariableIndex(1) => MathOptInterface.VariableIndex(1))))

julia> new_model[:ex]
2-element Array{GenericQuadExpr{Float64,VariableRef},1}:
 x² + x + 1
 2 x² + 2 x + 2
```
This seems to work for me.

**Comment by linde-fr** [comment]
Ah. Sorry. Now the GenericAffExpr works in my own code.
I tried the same example as you, and that works fine! 

In  my own code though, I still got the same error for the GenericQuadExpr. But I found out what the problem is.
I looked into the types of my expressions, and the problematic expression was of the form 
`    @expression(m, problematic[i=1:n_a,t=1:n_t],  - constant[i,t]*discomfort[i,t]^2)`
where 
`@expression(m, discomfort[i=1:n_a, t=1:n_t], Tᵢ[i,t] - constant2[i])`
The only variable here is `Tᵢ`, rest is constants.

Then I got this result
`julia> typeof(m[:problematic])
Array{Array{GenericQuadExpr{Float64,VariableRef},1},2}`
and this formulation leads to the error.

So the expression is seen as an array of dimension 1 instead of just a number... A bit hacky, but when I write 
` @expression(m, problematic[i=1:n_a,t=1:n_t],  sum(- constant[i,t]*discomfort[i,t]^2))`
then 
`typeof(m[:problematic])
Array{GenericQuadExpr{Float64,VariableRef},2}`
and the copy function works as it should.

Is there a better way I can make ` - constant[i,t]*discomfort[i,t]^2` be seen as a "scalar" instead of an Array of dim 1?

**Comment by odow** [comment]
Can you provide a complete minimal working example? That code looks like it should work, if `T[i,t]` is a scalar.

```Julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x)
x

julia> @expression(model, a[i=1:2, j=1:2], x - (i + j))
2×2 Array{GenericAffExpr{Float64,VariableRef},2}:
 x - 2  x - 3
 x - 3  x - 4

julia> @expression(model, b[i=1:2, j=1:2], - (i + j)*a[i, j])
2×2 Array{GenericAffExpr{Float64,VariableRef},2}:
 -2 x + 4  -3 x + 9
 -3 x + 9  -4 x + 16
```

**Comment by linde-fr** [comment]
So sorry, it turns out I made a mistake somewhere in the definition of my constants. `constant[i,j]` was a vector, where it should have been a scalar. Now all is well.

Thank you so much for your time. Next time I will start of making a minimal working example before bothering you!

**Comment by odow** [comment]
Hmm. I wasn't aware you could do this! It seems our expression handling is more generic than I realized:
```Julia
julia> @expression(model, d[i=1:2, j=1:2], Dict(i => x, j => 2x))
2×2 Array{Dict{Int64,AbstractJuMPScalar},2}:
 Dict(1=>2 x)       Dict(2=>2 x,1=>x)
 Dict(2=>x,1=>2 x)  Dict(2=>2 x)
```
I think it is still an issue:
```julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x)
x

julia> @expression(model, c[i=1:2, j=1:2], [i, j] * x)
2×2 Array{Array{GenericAffExpr{Float64,VariableRef},1},2}:
 [x, x]    [x, 2 x]
 [2 x, x]  [2 x, 2 x]

julia> copy_model(model)
ERROR: MethodError: no method matching getindex(::ReferenceMap, ::Array{GenericAffExpr{Float64,VariableRef},1})
Closest candidates are:
  getindex(::ReferenceMap, ::VariableRef) at /Users/oscar/.julia/dev/JuMP/src/copy.jl:27
  getindex(::ReferenceMap, ::ConstraintRef) at /Users/oscar/.julia/dev/JuMP/src/copy.jl:31
  getindex(::ReferenceMap, ::GenericAffExpr) at /Users/oscar/.julia/dev/JuMP/src/copy.jl:35
  ...
Stacktrace:
 [1] _broadcast_getindex_evalf at ./broadcast.jl:648 [inlined]
 [2] _broadcast_getindex at ./broadcast.jl:621 [inlined]
 [3] getindex at ./broadcast.jl:575 [inlined]
 [4] copy at ./broadcast.jl:876 [inlined]
 [5] materialize(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(getindex),Tuple{Base.RefValue{ReferenceMap},Array{Array{GenericAffExpr{Float64,VariableRef},1},2}}}) at ./broadcast.jl:837
 [6] copy_model(::Model) at /Users/oscar/.julia/dev/JuMP/src/copy.jl:114
 [7] top-level scope at REPL[21]:1
```

**Comment by linde-fr** [comment]
Yeah, this was also surprising to me! I was expecting I would get an error if an entry of an expression would not be a scalar, but indeed it is very generic. In my case the expression elements `problematic[i,j]` were vectors, which was causing the problem.

If I can be of any help, I'd be happy to. I would like to be involved but have no experience besides being a user.

**Comment by odow** [comment]
Here is where the error is thrown from: https://github.com/jump-dev/JuMP.jl/blob/d2398ad1a5e90a3fda51274ccc3b48b88e1abbb9/src/copy.jl#L113-L115
which calls these methods
https://github.com/jump-dev/JuMP.jl/blob/d2398ad1a5e90a3fda51274ccc3b48b88e1abbb9/src/copy.jl#L22-L51

Basically, when creating a new model, we loop through all the elements in `object_dictionary(model)`, and map their values to the new variables/constraints.

We probably need to add some new methods like this:
```Julia
function Base.getindex(map::ReferenceMap, val::AbstractArray)
    return getindex.(map, val)
end

function Base.getindex(map::ReferenceMap, val::T) where {T <: AbstractDict}
    return T(k => map[v] for (k, v) in val)
end

function Base.getindex(::ReferenceMap, val::Any)
    @warn(
        "I don't know how to map an object of type `$(typeof(val))` through " *
        "the reference map. Returning `nothing` instead."
    )
    return
end
```

Although I don't know if the warning is the best idea. Other people may have better suggestions.

**Comment by odow** [comment]
Developer call says skipping things we don't know how to copy is the correct thing to do.

**Comment by linde-fr** [comment]
so this would mean the last thing that you were suggesting? So to have the copied model not include this expression?
```
function Base.getindex(::ReferenceMap, val::Any)
    @warn(
        "I don't know how to map an object of type `$(typeof(val))` through " *
        "the reference map. Returning `nothing` instead."
    )
    return
end
```

This happens for example also for the chosen solver right now, so that would make sense. But I guess a warning would be needed.

**Comment by linde-fr** [comment]
Would it be ok that I try to add it and make a pull request? It is the first time I do that, so be patient with me :)

**Comment by odow** [comment]
> Would it be ok that I try to add it and make a pull request? 

Sure! Feel free to ask questions here.

We should add these two methods to https://github.com/jump-dev/JuMP.jl/blob/5fec8c011c4d0736c6d4f3aab8a622d8eee425a4/src/copy.jl#L27-L51
```Julia
function Base.getindex(map::ReferenceMap, val::AbstractArray)
    return getindex.(map, val)
end

function Base.getindex(::ReferenceMap, val::Any)
    @warn("Helpful warning")
    return
end
```
and then add a test function for each method somewhere here:
https://github.com/jump-dev/JuMP.jl/blob/5fec8c011c4d0736c6d4f3aab8a622d8eee425a4/test/model.jl#L576-L583
Perhaps something like (I haven't tried, so there might be a mistake):
```Julia
function test_copy_refmap_warn()
    model = Model()
    @expression(model, expr, "my_expression")
    new_model, ref_map = copy_model(model)
    @test ref_map[expr] === nothing
end
```

**Comment by linde-fr** [comment]
Great, thank you. I will get started today and let you know if I have any more questions!

**Comment by linde-fr** [comment]
should I create a branch? does it matter what it is called?

**Comment by odow** [comment]
Here are some instructions I gave @junglegobs https://github.com/jump-dev/JuMP.jl/issues/2371#issuecomment-769991624. (Just replace `junglegobs` with `linde-fr`.) It doesn't matter what you name the branch.

**Comment by odow** [comment]
@linde-fr let me know if you'd still like to work on this (I can talk you through the steps if you got stuck somewhere).

**Comment by linde-fr** [comment]
Hey, I am still on it, a lot of work got in the way. Doing it now!

**Comment by linde-fr** [comment]
I added a test to  the testing file that did not pass your updates, so I guess I can still help :) 
```
function test_copy_refmap_expr()
    model = Model()
    @variable(model, x)
    @expression(model, c[i=1:2, j=1:2], [i, j] * x)
    new_model, ref_map = copy_model(model)
    @test ref_map[expr] === nothing
end
```
Gives error 
```
MethodError: no method matching getindex(::ReferenceMap, ::Array{GenericAffExpr{Float64,VariableRef},1})
  Closest candidates are:
    getindex(::ReferenceMap, !Matched::VariableRef) at /home/linde/.julia/dev/JuMP/src/copy.jl:27
    getindex(::ReferenceMap, !Matched::ConstraintRef) at /home/linde/.julia/dev/JuMP/src/copy.jl:31
    getindex(::ReferenceMap, !Matched::GenericAffExpr) at /home/linde/.julia/dev/JuMP/src/copy.jl:35
    ...
```

**Comment by linde-fr** [comment]
Ah, I see I looked a the wrong branch, you already fixed the test I posted in the previous post.

So he only thing I added is a getindex function for things we don't know how to copy. I make it print the name of the thing that cannot be copied, if this name is available: 
```
function Base.getindex(::ReferenceMap, val::Any)
    valname = nothing
    try
        valname = name(val)
    catch
    end
    if isnothing(valname)
        @warn(
            "I don't know how to map an object of type `$(typeof(val))` through " *
            "the reference map. Returning `nothing` instead. This constraint " *
            "or expression " *
            "will not be included in the copied model."
            )
    else
        @warn(
            "I don't know how to map an object of type `$(typeof(val))` through " *
            "the reference map. Returning `nothing` instead. This constraint," *
            "in your case named `$(valname)`, " *
            "will not be included in the copied model."
        )
    end
    return
end
```

I also added two tests:
```
function test_copy_refmap_expr()
    model = Model()
    @variable(model, x)
    @expression(model, expr[i=1:2, j=1:2], [i, j] * x)
    new_model, ref_map = copy_model(model)
    @test ref_map[expr] == new_model[:expr]
    for i=1:2, j=1:2
        @test new_model[:expr][i,j] ==  [i, j] * new_model[:x]
    end
end

function test_copy_unknown_val()
    model = Model()
    @variable(model, x)
    @expression(model, dictExpr[i=1:2, j=1:2], Dict(i => x, j => 2x))
    new_model, ref_map = copy_model(model)
    @test ref_map[:dictExpr] === nothing
end
```
However, after I add my getindex function, your test "test_copy_object_fail()" does not pass now. 

Not sure this is of any help. Let me know if I should make a pull request for this.

**Comment by odow** [comment]
Yes, sorry. I started on #2019, and then realized it was the same underlying cause as this, so I accidentally fixed both.

I decided against returning `nothing` because it's less likely to lead to bugs (accessing `model[:dictExpr]` will throw an error, rather than returning something incorrect). The warning currently looks like:
```Julia
julia> new_model, ref_map = copy_model(model)
┌ Warning: Unable to copy `:dictExpr` of type Array{Dict{Int64,AbstractJuMPScalar},2} in the model. Please open a Github issue at https://github.com/jump-dev/JuMP.jl with this message.
└ @ JuMP ~/.julia/dev/JuMP/src/copy.jl:157
```

The two extra tests would be useful. You can make a PR to my branch by going to https://github.com/jump-dev/JuMP.jl/blob/od/refmap/test/model.jl and clicking the pencil (edit) in the top-right. Then copy these two tests in near the others:
```Julia
function test_copy_refmap_expr()
    model = Model()
    @variable(model, x)
    @expression(model, expr[i=1:2, j=1:2], [i, j] * x)
    new_model, ref_map = copy_model(model)
    @test ref_map[expr] == new_model[:expr]
    for i=1:2, j=1:2
        @test new_model[:expr][i,j] ==  [i, j] * new_model[:x]
    end
end

function test_copy_unknown_val()
    model = Model()
    @variable(model, x)
    @expression(model, dictExpr[i=1:2, j=1:2], Dict(i => x, j => 2x))
    new_model, ref_map = copy_model(model)
    @test !haskey(new_model, :dictExpr)
end
```
That way you can get credit for the work you put into this.

**Comment by linde-fr** [comment]
No problem, I should just have started a month ago!
I agree it is better to throw an error, I would not expect that other behavior of the copy function as a user.

Did as you said, and I ran the tests and all passed. Hope it is all set now? 

At least I have a better idea of how to help out next time!
